### ISSUE TITLE
Don't dynamically create atoms

### ISSUE THREAD

**Issue by hunterboerner** [johnwahba/async_with#1]
We can use the name variable name as provided by user but with a different context. E.g.

```elixir
Macro.var(atom_var, AsyncWith.Future)
```

https://github.com/johnwahba/async_with/blob/f040d30ef3153595bac34417e5e84a2509d435b5/lib/async_with.ex#L112

/cc @josevalim. I may be misunderstanding variable contexts.

**Comment by josevalim** [comment]
I think generating those atoms are fine since it is happening inside a macro at compilation time.

**Comment by hunterboerner** [comment]
@josevalim do variable names get munged when the BEAM bytecode is generated?

**Comment by hunterboerner** [comment]
Closing as José is law.

**Comment by josevalim** [comment]
Variable names from any context besides the user one are munged, yes.
